'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, Users, Sparkles, Shield, DoorOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { defaults } from '@/lib/engine';
import { SettingsForm, type Send } from './shared';
export function Entry({send,busy,error}:{send:Send;busy:boolean;error:string}){
 const [screen,setScreen]=useState('home'),[name,setName]=useState(''),[code,setCode]=useState(''),[config,setConfig]=useState(defaults);
 useEffect(()=>{setName(localStorage.getItem('castle-name')||'');},[]);
 const enter=(type:string,demo=false)=>{localStorage.setItem('castle-name',name);void send(type,{name,code:code.trim().toUpperCase(),settings:config,demo});};
 return <><section className="home"><div className="intro"><span className="eyebrow gold">THE CASTLE GATES ARE OPEN</span><h1>Trust your friends.<br/><em>Question everything.</em></h1><p>Wizards protect the gold. Dragons hide among them.<br/>Who will you believe when night falls?</p><div className="art"><img src="/castle.png" alt="A storybook castle with warm lit rooms and a dragon overhead"/></div><div className="facts"><span><Users size={17}/> 4–12 players</span><span><Shield size={17}/> Secret roles</span><span><Sparkles size={17}/> No account needed</span></div></div><aside className="panel gate"><span className="eyebrow">YOUR STORY STARTS HERE</span><h2>{screen==='create'?'Prepare your castle':screen==='join'?'Find your fellowship':'Enter the castle'}</h2><p className="muted">Gather your friends. Keep your secrets.</p>{error&&<div className="error" role="alert">{error}</div>}<label>Your adventurer name<input autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="What shall we call you?" maxLength={20}/></label>{screen==='home'?<><Button className="primary" onClick={()=>setScreen('create')}>Create a game <ArrowRight/></Button><Button className="secondary" onClick={()=>setScreen('join')}>Join with a code <DoorOpen/></Button><div className="divider">OR EXPLORE ON YOUR OWN</div><Button className="quiet full" disabled={busy||name.trim().length<2} onClick={()=>enter('create',true)}><Sparkles/> {busy?'Opening the gates…':'Play with simulated players'}</Button><p className="tiny">One device. Five companions. All the intrigue.</p></>:screen==='join'?<form onSubmit={e=>{e.preventDefault();enter('join');}}><label>Session code<input autoCapitalize="characters" value={code} maxLength={6} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABC234" className="code-input"/></label><Button type="submit" className="primary" disabled={busy||name.trim().length<2||code.length!==6}>Join the castle <ArrowRight/></Button></form>:<><SettingsForm value={config} onChange={setConfig}/><Button className="primary" disabled={busy||name.trim().length<2} onClick={()=>enter('create')}>Open the lobby <ArrowRight/></Button></>}{screen!=='home'&&<Button className="quiet full topgap" onClick={()=>setScreen('home')}>Back</Button>}</aside></section><footer className="footer">KEEP YOUR GOLD CLOSE. YOUR SECRETS CLOSER.</footer></>;
}
